version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub

python:
  install:
    - requirements: docs/source/requirements.txt
