#!/bin/bash
mypath=`pwd`
#./example_build_ibm_mgma.sh
module load cmake cuda  gcc netlib-lapack netlib-lapack essl
module unload magma
export OLCF_MAGMA_ROOT=${OLCF_MAGMA_ROOT:="$PROJWORK/csc304/magma/magma-2.5.1-alpha1"}

./example_build_gnu_mgma.sh
#./example_build_gnu.sh
cd build; make -j; make install
cd $mypath
cd ../qmd-progress
./example_build_gnu_mgma.sh 
#./example_build_gnu.sh 
cd build; make -j; make install
