FROM ubuntu:focal
RUN apt-get update
RUN apt-get install --assume-yes --no-install-recommends apt-utils
RUN apt-get install --assume-yes --no-install-recommends build-essential
RUN apt-get install --assume-yes --no-install-recommends git-core openssh-client
RUN apt-get install --assume-yes --no-install-recommends cmake cmake-data libblas-dev liblapack-dev
RUN apt-get install --assume-yes --no-install-recommends gfortran
RUN apt-get install --assume-yes --no-install-recommends doxygen
RUN apt-get install --assume-yes --no-install-recommends texlive
