var namespacebml__c__interface__m =
[
    [ "bml_add_C", "interfacebml__c__interface__m_1_1bml__add__C.html", "interfacebml__c__interface__m_1_1bml__add__C" ],
    [ "bml_add_identity_C", "interfacebml__c__interface__m_1_1bml__add__identity__C.html", "interfacebml__c__interface__m_1_1bml__add__identity__C" ],
    [ "bml_adjungate_triangle_C", "interfacebml__c__interface__m_1_1bml__adjungate__triangle__C.html", "interfacebml__c__interface__m_1_1bml__adjungate__triangle__C" ],
    [ "bml_banded_matrix_C", "interfacebml__c__interface__m_1_1bml__banded__matrix__C.html", "interfacebml__c__interface__m_1_1bml__banded__matrix__C" ],
    [ "bml_convert_from_dense_C", "interfacebml__c__interface__m_1_1bml__convert__from__dense__C.html", "interfacebml__c__interface__m_1_1bml__convert__from__dense__C" ],
    [ "bml_convert_to_dense_C", "interfacebml__c__interface__m_1_1bml__convert__to__dense__C.html", "interfacebml__c__interface__m_1_1bml__convert__to__dense__C" ],
    [ "bml_copy_new_C", "interfacebml__c__interface__m_1_1bml__copy__new__C.html", "interfacebml__c__interface__m_1_1bml__copy__new__C" ],
    [ "bml_deallocate_C", "interfacebml__c__interface__m_1_1bml__deallocate__C.html", "interfacebml__c__interface__m_1_1bml__deallocate__C" ],
    [ "bml_diagonalize_C", "interfacebml__c__interface__m_1_1bml__diagonalize__C.html", "interfacebml__c__interface__m_1_1bml__diagonalize__C" ],
    [ "bml_gershgorin_C", "interfacebml__c__interface__m_1_1bml__gershgorin__C.html", "interfacebml__c__interface__m_1_1bml__gershgorin__C" ],
    [ "bml_get_bandwidth_C", "interfacebml__c__interface__m_1_1bml__get__bandwidth__C.html", "interfacebml__c__interface__m_1_1bml__get__bandwidth__C" ],
    [ "bml_get_double_complex_C", "interfacebml__c__interface__m_1_1bml__get__double__complex__C.html", "interfacebml__c__interface__m_1_1bml__get__double__complex__C" ],
    [ "bml_get_double_real_C", "interfacebml__c__interface__m_1_1bml__get__double__real__C.html", "interfacebml__c__interface__m_1_1bml__get__double__real__C" ],
    [ "bml_get_N_C", "interfacebml__c__interface__m_1_1bml__get__N__C.html", "interfacebml__c__interface__m_1_1bml__get__N__C" ],
    [ "bml_get_row_bandwidth_C", "interfacebml__c__interface__m_1_1bml__get__row__bandwidth__C.html", "interfacebml__c__interface__m_1_1bml__get__row__bandwidth__C" ],
    [ "bml_get_row_C", "interfacebml__c__interface__m_1_1bml__get__row__C.html", "interfacebml__c__interface__m_1_1bml__get__row__C" ],
    [ "bml_get_single_complex_C", "interfacebml__c__interface__m_1_1bml__get__single__complex__C.html", "interfacebml__c__interface__m_1_1bml__get__single__complex__C" ],
    [ "bml_get_single_real_C", "interfacebml__c__interface__m_1_1bml__get__single__real__C.html", "interfacebml__c__interface__m_1_1bml__get__single__real__C" ],
    [ "bml_identity_matrix_C", "interfacebml__c__interface__m_1_1bml__identity__matrix__C.html", "interfacebml__c__interface__m_1_1bml__identity__matrix__C" ],
    [ "bml_multiply_C", "interfacebml__c__interface__m_1_1bml__multiply__C.html", "interfacebml__c__interface__m_1_1bml__multiply__C" ],
    [ "bml_print_bml_matrix_C", "interfacebml__c__interface__m_1_1bml__print__bml__matrix__C.html", "interfacebml__c__interface__m_1_1bml__print__bml__matrix__C" ],
    [ "bml_print_bml_vector_C", "interfacebml__c__interface__m_1_1bml__print__bml__vector__C.html", "interfacebml__c__interface__m_1_1bml__print__bml__vector__C" ],
    [ "bml_print_dense_matrix_C", "interfacebml__c__interface__m_1_1bml__print__dense__matrix__C.html", "interfacebml__c__interface__m_1_1bml__print__dense__matrix__C" ],
    [ "bml_random_matrix_C", "interfacebml__c__interface__m_1_1bml__random__matrix__C.html", "interfacebml__c__interface__m_1_1bml__random__matrix__C" ],
    [ "bml_read_bml_matrix_C", "interfacebml__c__interface__m_1_1bml__read__bml__matrix__C.html", "interfacebml__c__interface__m_1_1bml__read__bml__matrix__C" ],
    [ "bml_scale_C", "interfacebml__c__interface__m_1_1bml__scale__C.html", "interfacebml__c__interface__m_1_1bml__scale__C" ],
    [ "bml_scale_inplace_C", "interfacebml__c__interface__m_1_1bml__scale__inplace__C.html", "interfacebml__c__interface__m_1_1bml__scale__inplace__C" ],
    [ "bml_set_row_C", "interfacebml__c__interface__m_1_1bml__set__row__C.html", "interfacebml__c__interface__m_1_1bml__set__row__C" ],
    [ "bml_threshold_C", "interfacebml__c__interface__m_1_1bml__threshold__C.html", "interfacebml__c__interface__m_1_1bml__threshold__C" ],
    [ "bml_trace_C", "interfacebml__c__interface__m_1_1bml__trace__C.html", "interfacebml__c__interface__m_1_1bml__trace__C" ],
    [ "bml_transpose_new_C", "interfacebml__c__interface__m_1_1bml__transpose__new__C.html", "interfacebml__c__interface__m_1_1bml__transpose__new__C" ],
    [ "bml_write_bml_matrix_C", "interfacebml__c__interface__m_1_1bml__write__bml__matrix__C.html", "interfacebml__c__interface__m_1_1bml__write__bml__matrix__C" ],
    [ "bml_zero_matrix_C", "interfacebml__c__interface__m_1_1bml__zero__matrix__C.html", "interfacebml__c__interface__m_1_1bml__zero__matrix__C" ]
];